# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_E(object):
    def setupUi(self, E):
        E.setObjectName("E")
        E.resize(411, 313)
        self.gridLayout = QtWidgets.QGridLayout(E)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButtonadd = QtWidgets.QRadioButton(E)
        self.radioButtonadd.setObjectName("radioButtonadd")
        self.gridLayout.addWidget(self.radioButtonadd, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(E)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 4, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(E)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 5)
        self.buttonBox = QtWidgets.QDialogButtonBox(E)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 5)
        self.radioButtonedit = QtWidgets.QRadioButton(E)
        self.radioButtonedit.setObjectName("radioButtonedit")
        self.gridLayout.addWidget(self.radioButtonedit, 0, 1, 1, 1)
        self.coffeeID = QtWidgets.QSpinBox(E)
        self.coffeeID.setObjectName("coffeeID")
        self.gridLayout.addWidget(self.coffeeID, 0, 2, 1, 2)

        self.retranslateUi(E)
        self.buttonBox.accepted.connect(E.accept) # type: ignore
        self.buttonBox.rejected.connect(E.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(E)

    def retranslateUi(self, E):
        _translate = QtCore.QCoreApplication.translate
        E.setWindowTitle(_translate("E", "Dialog"))
        self.radioButtonadd.setText(_translate("E", "Add"))
        self.label.setText(_translate("E", "coffee ID"))
        self.radioButtonedit.setText(_translate("E", "Edit"))
